### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by KaschiCZE** [tomaskadlec/lunch_guy#56]
While attempting to retrieve latest version of the menu using refresh button next to the date, I keep getting 500 internal server error. F5 refreshing works fine.
![image](https://cloud.githubusercontent.com/assets/11159274/15009917/a25f672c-11e9-11e6-922d-f1d7f045a2bf.png)

It looks like problem with the deleteAction.

**Comment by KaschiCZE** [comment]
I take it back, problem is with redirecting back to the main menu page. When i reopen the page, it's reloading the designated menu.

**Comment by hroncok** [comment]
Happens to me as well. Also note the URL that says delete.
